### PR TITLE
Added skip param to status command + more directories to skip

### PR DESCRIPTION
**Pull request by CodyBontecou**

### CODE REVIEW

**Comment by CodyBontecou** [comment]
@BruceEckel I'm curious as to why my .git directory was giving me errors while yours wasn't. Could this be an OS-specific error?

**Comment by BruceEckel** [comment]
OS-specific is the most likely cause. I try to make things OS-agnostic but
I'm not always successful.

-- Bruce Eckel
MindViewLLC.com
blog.BruceEckel.com <http://blog.bruceeckel.com/>
SoftwareArchitectureForum.com <http://www.SoftwareArchitectureForum.com>
WinterTechForum.com <http://www.WinterTechForum.com>
OnJava8.com <http://www.OnJava8.com>
www.AtomicScala.com
Reinventing-Business.com <http://www.Reinventing-Business.com>

**Comment by CodyBontecou** [comment]
I see. Maybe there's a way to avoid iterating over hidden files entirely.

**Comment by BruceEckel** [comment]
There should be, either by pattern or by detecting that it has hidden
status.

-- Bruce Eckel
MindViewLLC.com
blog.BruceEckel.com <http://blog.bruceeckel.com/>
SoftwareArchitectureForum.com <http://www.SoftwareArchitectureForum.com>
WinterTechForum.com <http://www.WinterTechForum.com>
OnJava8.com <http://www.OnJava8.com>
www.AtomicScala.com
Reinventing-Business.com <http://www.Reinventing-Business.com>

**Comment by CodyBontecou** [comment]
Solved it with a not statement. It also works with: 

    [x for x in Path(os.environ['GIT_HOME']).glob('[!.]*') if x.is_dir()]

but I wasn't sure if it was faster or as readable.

**Comment by CodyBontecou** [comment]
Let me figure out how to break these commits up into multiple PR's... It's kind of inconvenient that every new push it sent to this PR, but my guess is it's because I'm updating my master branch which is what this PR continues to update itself on.

**Pull request closed without merging**
